require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe TimeTablesController, type: :controller do

  login_user

  # This should return the minimal set of attributes required to create a valid
  # TimeTable. As you add validations to TimeTable, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:time_table, :valid)
  }

  let(:invalid_attributes) {
    attributes_for(:time_table, :invalid)
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TimeTablesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      time_table = TimeTable.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      time_table = TimeTable.create! valid_attributes
      get :show, params: {id: time_table.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      time_table = TimeTable.create! valid_attributes
      get :edit, params: {id: time_table.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new TimeTable" do
        expect {
          post :create, params: {time_table: valid_attributes}, session: valid_session
        }.to change(TimeTable, :count).by(1)
      end

      it "redirects to the created time_table" do
        post :create, params: {time_table: valid_attributes}, session: valid_session
        expect(response).to redirect_to(TimeTable.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {time_table: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        attributes_for(:time_table, :valid_update)
      }

      it "updates the requested time_table" do
        time_table = TimeTable.create! valid_attributes
        a_time = time_table.arrival_time
        d_time = time_table.departure_time
        put :update, params: {id: time_table.to_param, time_table: new_attributes}, session: valid_session
        time_table.reload
        expect(time_table.arrival_time).not_to be_eql a_time
        expect(time_table.departure_time).not_to be_eql d_time
      end

      it "redirects to the time_table" do
        time_table = TimeTable.create! valid_attributes
        put :update, params: {id: time_table.to_param, time_table: valid_attributes}, session: valid_session
        expect(response).to redirect_to(time_table)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        time_table = TimeTable.create! valid_attributes
        put :update, params: {id: time_table.to_param, time_table: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested time_table" do
      time_table = TimeTable.create! valid_attributes
      expect {
        delete :destroy, params: {id: time_table.to_param}, session: valid_session
      }.to change(TimeTable, :count).by(-1)
    end

    it "redirects to the time_tables list" do
      time_table = TimeTable.create! valid_attributes
      delete :destroy, params: {id: time_table.to_param}, session: valid_session
      expect(response).to redirect_to(time_tables_url)
    end
  end

end
